try {

    console.log(a+b);
}

catch(err){
    console.log(err);

    console.log('An error was identify');
    console.log('The server is working on it');
}

console.log('But this doesn not stop our code ');

